### ISSUE TITLE
Deploy mainnet subgraph + signal indexers

### ISSUE THREAD

**Issue by nikbora** [forgottenrunes/forgotten-runes-website#14]
- [] Depends on https://github.com/forgottenrunes/forgotten-runes-website/issues/17
- [] Setup moustache templating in the subgraph repo to allow Rinkeby/Mainnet deploys (examples in the Graph docs)
- [] Deploy mainnet subraph via The Graph Studio and use their rate limited test endpoint initially (?)
- [] Signal with GRT for indexers to keep indexing

**Comment by forgottendev** [comment]
Deployed and signalled 2k GRT (and was immediately front-run) - have another 6k in the hopper if we need it
