### ISSUE TITLE
Lore contract improvements

### ISSUE THREAD

**Issue by nikbora** [forgottenrunes/forgotten-runes-website#21]
- [x] Figure out how "sponsored gas" for lore submissions could work

**Comment by forgottendev** [comment]
Should be possible using `ecrecover`.

Some resources (need investigation):

https://gist.github.com/BjornvdLaan/e41d292339bbdebb831d0b976e1804e8
https://github.com/sogoiii/ecrecover-example
https://github.com/ethers-io/ethers.js/issues/468
https://ethereum.stackexchange.com/questions/15364/ecrecover-from-geth-and-web3-eth-sign/30445
https://soliditydeveloper.com/ecrecover

**Comment by forgottendev** [comment]
But a key security precaution is to prevent replay attacks.

Without proper precautions, a replay attack could:

- add the some lore more than once
- replace lore that was already updated/modified (metadataurl)

My instinct is that we can prevent replays by:

- only allowing sponsored gas on create, and
- require that the Lore ID be included in the signature and use that as a nonce

Only a nonce greater than the current Lore index can be used.

**Comment by aranair** [comment]
> Should be possible using `ecrecover`.

yeah looks possible w the eip712 draft it seems - https://soliditydeveloper.com/meta-transactions

(also found this potentially useful lib https://github.com/Mrtenz/eip-712)
