### ISSUE TITLE
Upload the images as separate files and then reference them in the markdown

### ISSUE THREAD

**Issue by forgottendev** [forgottenrunes/forgotten-runes-website#32]
Right now, the images _will_ upload but only as a huge data:uri. This is sort of bad because it makes the JSON unwieldily, also we're going to want to use custom rendering components like next/image or maybe a CDN etc.

So this task is to read the markdown image URLs and then upload them separately, then replace the URLs. The good news is that there's a convenient hook for this here:

https://github.com/forgottenrunes/forgotten-runes-website/blob/2596b47d29286d6c3d30c328464f5e7749bdfe73/components/AddLore/AddLoreEditor.tsx#L116

We just need to convert that function to async.

**Comment by nikbora** [comment]
Some issues with doing it on the client:

1. We would have to expose an IPFS uploading key to re-upload images (or do via our server but then may as well do it all on the server anyway)
2. We would keep uploading images any time people edit/change/move different images and it would then be tricky to figure out which IPFS hashes were for final story and which were just whilst drafting...

For now I have done image replacement/uploading on server side when uploading lore: https://github.com/forgottenrunes/forgotten-runes-website/pull/38

**Comment by nikbora** [comment]
Ok, ignore the above :) I have realised that what we are saying is that we will upload local files only to IPFS and then replace those in markdown 👍🏻

**Comment by nikbora** [comment]
Fixed in https://github.com/forgottenrunes/forgotten-runes-website/pull/39
