### ISSUE TITLE
Page color on inner binding 

### ISSUE THREAD

**Issue by cryppadotta** [forgottenrunes/forgotten-runes-website#43]
![Screen Shot 2021-09-15 at 08 48 01 ](https://user-images.githubusercontent.com/34892728/133445431-b4032f69-c2a8-4037-948f-8168db816fd0.png)

Should be red for that left interior

**Comment by forgottendev** [comment]
Fix in `components/Lore/Book.tsx`, but depends on #42 with SSR resolving the IPFS of each Lore
